# Generated by Django 3.0.8 on 2020-07-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_image', models.ImageField(upload_to='')),
                ('prep_time', models.DurationField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('type_of_food', models.CharField(choices=[('AP', 'Appetizer'), ('EN', 'Entree'), ('DS', 'Dessert'), ('DR', 'Drink'), ('SN', 'Snack')], default='EN', max_length=2)),
                ('availability', models.CharField(choices=[('ST', 'Staple'), ('SP', 'Special')], default='ST', max_length=2)),
            ],
        ),
    ]
